version: "3"
services:
  nginx:
    build: ./.nginx
    volumes:
      - shots:/mnt/shots
    ports:
      - 80:80
    depends_on:
      - capture

  capture:
    build: ./
    environment:
      - LOG_LEVEL=debug
      - RABBITMQ_HOST=queue
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - STORAGE_PATH=/mnt/shots
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESSKEY=miniokey
      - MINIO_SECRET=miniosecret
      - WORKERS_PER_INSTANCE=3
    volumes:
      - shots:/mnt/shots
    depends_on:
      - queue
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mongo
    ports:
      - 27017:27017

  minio:
    image: minio/minio
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=miniokey
      - MINIO_SECRET_KEY=miniosecret

volumes:
  shots:
