version: "3"
services:
  nginx:
    build: ./.nginx
    volumes:
      - shots:/mnt/shots
    ports:
      - 80:80
    depends_on:
      - capture

  capture:
    build: ./
    environment:
      - LOG_LEVEL=debug
      - RABBITMQ_HOST=queue
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - STORAGE_PATH=/mnt/shots
    volumes:
      - shots:/mnt/shots
    depends_on:
      - queue
      - db

  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mongo
    ports:
      - 27017:27017

volumes:
  shots:
