version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  heimdall:
    image: gcr.io/cloud-voyage/heimdall
    environment:
      - HTTP_LISTEN_PORT=80
      - QUEUE_GRPC_ADDRESS=huginn:5000
    ports:
      - 8080:80

  huginn:
    image: gcr.io/cloud-voyage/huginn
    environment:
      - GRPC_LISTEN_PORT=5000
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest

  muninn:
    image: gcr.io/cloud-voyage/muninn
    environment:
      - CAPTURE_GRPC_ADDRESS=thor:5000
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
  thor:
    image: thor
    volumes:
      - ./gcloud-config.json:/app/gcloud-config.json
    environment:
      - GRPC_LISTEN_PORT=5000
      - GCP_SERVICE_ACCOUNT_FILE_PATH=/app/gcloud-config.json
      - GCP_STORAGE_BUCKET_NAME=capture.2hamed.nl
