// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CaptureClient is the client API for Capture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaptureClient interface {
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
}

type captureClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureClient(cc grpc.ClientConnInterface) CaptureClient {
	return &captureClient{cc}
}

func (c *captureClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, "/Capture/Capture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureServer is the server API for Capture service.
// All implementations must embed UnimplementedCaptureServer
// for forward compatibility
type CaptureServer interface {
	Capture(context.Context, *CaptureRequest) (*CaptureResponse, error)
	mustEmbedUnimplementedCaptureServer()
}

// UnimplementedCaptureServer must be embedded to have forward compatible implementations.
type UnimplementedCaptureServer struct {
}

func (UnimplementedCaptureServer) Capture(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedCaptureServer) mustEmbedUnimplementedCaptureServer() {}

// UnsafeCaptureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureServer will
// result in compilation errors.
type UnsafeCaptureServer interface {
	mustEmbedUnimplementedCaptureServer()
}

func RegisterCaptureServer(s grpc.ServiceRegistrar, srv CaptureServer) {
	s.RegisterService(&Capture_ServiceDesc, srv)
}

func _Capture_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Capture/Capture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Capture_ServiceDesc is the grpc.ServiceDesc for Capture service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capture_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Capture",
	HandlerType: (*CaptureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capture",
			Handler:    _Capture_Capture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/capture.proto",
}
