apiVersion: v1
kind: Service
metadata:
  name: rabbit-admin
  labels:
    {{- include "odin.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: admin
      protocol: TCP
      name: http
  selector:
    {{- include "odin.selectorLabels" . | nindent 4 }}
