apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn
  labels:
    {{- include "odin.labels" . | nindent 4 }}
    app: huginn
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "odin.selectorLabels" . | nindent 6 }}
      app: huginn
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odin.selectorLabels" . | nindent 8 }}
        app: huginn
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "odin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: huginn
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.huginn.repository }}:{{ .Values.image.huginn.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.huginn.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.env.grpcListenPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GRPC_LISTEN_PORT
              value: {{ .Values.env.grpcListenPort | quote }}
            - name: RABBITMQ_HOST
              value: {{ .Values.env.rabbitHost | quote }} 
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: {{ .Values.auth.username | quote }}
            - name: RABBITMQ_PASS
              value: {{ .Values.auth.password | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
