apiVersion: v1
kind: Service
metadata:
  name: huginn
  labels:
    {{- include "odin.labels" . | nindent 4 }}
    app: huginn
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "odin.selectorLabels" . | nindent 4 }}
    app: huginn
