apiVersion: v1
kind: Service
metadata:
  name: huginn
  labels:
    {{- include "odin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odin.selectorLabels" . | nindent 4 }}
