apiVersion: apps/v1
kind: Deployment
metadata:
  name: thor
  labels:
    {{- include "thor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "thor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.env.grpcListenPort }}
              protocol: TCP
          env:
            - name: GRPC_LISTEN_PORT
              value: {{ .Values.env.grpcListenPort | quote}}
            - name: GCP_STORAGE_BUCKET_NAME
              value: {{ .Values.env.gcp.storageBucket | quote}}
            - name: GCP_SERVICE_ACCOUNT_FILE_PATH
              value: "/gcp/gcloud-config.json"
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.env.gcp.cloudProjectId }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: google-application-credentials
              mountPath: /gcp
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: google-application-credentials
          secret:
            secretName: {{ .Chart.Name }}